### ISSUE TITLE
No Such File?

### ISSUE THREAD

**Issue by rpattcorner** [kidk/felt#22]
Must be something obvious.  Any idea what's going on here?

Install on CentOS looks like:

[root@localhost felt]# ls
examples  main.py    README.md  tests        VERSION
LICENSE   phantomjs  test.py    Vagrantfile  worker.js
[root@localhost felt]# python main.py --verbose examples/basic.json             ################################
        Felt (alpha)
################################

{'test': False, 'threads': 5, 'verbose': True, 'scenario': 'examples/basic.json', 'debug': False, 'userAgent': None, 'maxTime': 0, 'screenshot': False, 'browser': 'phantomjs'}

################################
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 811, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 764, in run
    self.__target(*self.__args, **self.__kwargs)
  File "main.py", line 216, in execute
    stderr=subprocess.STDOUT
  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by kidk** [comment]
Hi, thanks for your question. 

It seems Felt can't find the slimerjs executable. It needs to be available in your $PATH, try running `phantomjs --version` to see if it works.

**Comment by rpattcorner** [comment]
Wow, that was fast!

[vagrant@localhost felt]$ phantomjs --version
-bash: phantomjs: command not found
[vagrant@localhost felt]$ ./phantomjs --version
2.1.1
[vagrant@localhost felt]$

So ... it looks like phantomjs needs to be addressable as a binary in the path, not just present in the felt dir?

R.

**Comment by kidk** [comment]
Happen to be online 😄 

> So ... it looks like phantomjs needs to be addressable as a binary in the path, not just present in the felt dir?

Yes exactly. 

It was implemented this way to allow the use of many servers to run the Felt scenarios.

**Comment by rpattcorner** [comment]
Bingo! (duh).  Many thanks!

Going to throw this at a complicated little Angular app with login, CSRF tokens and who knows what, built on JHipster.  If you happen to have a more complex scenario in your back pocket, feel free to share it.  If not, much appreciate the getting started help!

R.

**Comment by kidk** [comment]
You're welcome. 

The most complicated scenario I have at the moment is the Magento one: https://github.com/kidk/felt/blob/master/examples/magento_checkout.json

If you get stuck somewhere, feel free to open a ticket. 
I'm going to close this one as you've found the solution 😄
